v = input('digite algo:')
print (type(v))
print('is numeric?')
print(v.isnumeric())
print('is alpha?')
print(v.isalpha())
print('is upper?')
print(v.isupper())
print('is alphanumeric?')
print(v.isalnum())
print('is decimal?')
print(v.isdecimal())